spring.application.name=MarshmelloWas

spring.datasource.url=${SPRING_DATASOURCE_URL:jdbc:postgresql://localhost:5432/marshmello}
spring.datasource.username=${SPRING_DATASOURCE_USERNAME:marshmello}
spring.datasource.password=${SPRING_DATASOURCE_PASSWORD:}

spring.jpa.hibernate.ddl-auto=none
spring.jpa.open-in-view=false
