CREATE TABLE users (
    user_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    nickname VARCHAR(15) NOT NULL,
    expected_delivery_date DATE
);

CREATE TABLE social_account (
    provider VARCHAR(50) NOT NULL,
    provider_user_id VARCHAR(255) NOT NULL,
    user_id BIGINT NOT NULL,
    PRIMARY KEY (provider, provider_user_id),
    CONSTRAINT fk_social_account_user
        FOREIGN KEY (user_id)
        REFERENCES users(user_id)
        ON DELETE CASCADE
);

CREATE INDEX idx_social_account_user_id
    ON social_account(user_id);

CREATE TABLE report (
    report_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    content TEXT NOT NULL,
    period_start DATE NOT NULL,
    period_end DATE NOT NULL,
    user_id BIGINT NOT NULL,
    CONSTRAINT fk_report_user
        FOREIGN KEY (user_id)
        REFERENCES users(user_id)
        ON DELETE CASCADE,
    CONSTRAINT ck_report_period
        CHECK (period_start <= period_end),
    CONSTRAINT uq_report_user_period
        UNIQUE (user_id, period_start, period_end)
);

CREATE INDEX idx_report_user_period_start
    ON report(user_id, period_start DESC);

CREATE TABLE check_in (
    checkin_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    achieved BOOLEAN NOT NULL,
    checkin_date DATE NOT NULL,
    diary VARCHAR(255),
    emotion SMALLINT NOT NULL,
    user_id BIGINT NOT NULL,
    CONSTRAINT fk_check_in_user
        FOREIGN KEY (user_id)
        REFERENCES users(user_id)
        ON DELETE CASCADE
);

CREATE INDEX idx_check_in_user_date
    ON check_in(user_id, checkin_date DESC);

CREATE TABLE images (
    image_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    image_data BYTEA NOT NULL,
    checkin_id BIGINT NOT NULL,
    CONSTRAINT fk_images_checkin
        FOREIGN KEY (checkin_id)
        REFERENCES check_in(checkin_id)
        ON DELETE CASCADE,
    CONSTRAINT uq_images_checkin
        UNIQUE (checkin_id),
    CONSTRAINT ck_images_max_1mib
        CHECK (octet_length(image_data) <= 1048576)
);

CREATE TABLE images_analysis (
    image_id BIGINT PRIMARY KEY,
    score SMALLINT NOT NULL,
    CONSTRAINT fk_images_analysis_image
        FOREIGN KEY (image_id)
        REFERENCES images(image_id)
        ON DELETE CASCADE,
    CONSTRAINT ck_images_analysis_score_nonnegative
        CHECK (score >= 0)
);

-- Body map / massage area shared code
-- 1: 가슴, 2: 복부, 3: 골반, 4: 엉덩이,
-- 5: 왼팔, 6: 오른팔, 7: 왼다리, 8: 오른다리
CREATE TABLE body_diary (
    body_region SMALLINT NOT NULL,
    checkin_id BIGINT NOT NULL,
    stretch_mark BOOLEAN,
    comment VARCHAR(50),
    PRIMARY KEY (body_region, checkin_id),
    CONSTRAINT ck_body_diary_region
        CHECK (body_region BETWEEN 1 AND 8),
    CONSTRAINT fk_body_diary_checkin
        FOREIGN KEY (checkin_id)
        REFERENCES check_in(checkin_id)
        ON DELETE CASCADE
);

CREATE TABLE actions (
    action_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    action_score SMALLINT NOT NULL,
    category VARCHAR(20) NOT NULL,
    guide_text TEXT NOT NULL,
    source VARCHAR(50) NOT NULL,
    helpfulness_score SMALLINT,
    CONSTRAINT ck_action_score_nonnegative
        CHECK (action_score >= 0),
    CONSTRAINT ck_helpfulness_score_nonnegative
        CHECK (helpfulness_score IS NULL OR helpfulness_score >= 0)
);

CREATE TABLE care_card (
    care_card_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    action_name VARCHAR(50) NOT NULL,
    action_reason TEXT NOT NULL,
    source VARCHAR(50) NOT NULL,
    checkin_id BIGINT NOT NULL,
    action_id BIGINT NOT NULL,
    CONSTRAINT fk_care_card_checkin
        FOREIGN KEY (checkin_id)
        REFERENCES check_in(checkin_id)
        ON DELETE CASCADE,
    CONSTRAINT fk_care_card_action
        FOREIGN KEY (action_id)
        REFERENCES actions(action_id)
        ON DELETE RESTRICT,
    CONSTRAINT uq_care_card_checkin
        UNIQUE (checkin_id)
);

CREATE INDEX idx_care_card_action_id
    ON care_card(action_id);
